# -*- coding: utf-8 -*-
"""Ambatucer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9ivHKCEq8zSHQbUqvX4ekXa2Z6YiP9d
"""

import time, os, sys

def is_colab():
    try:
        import google.colab
        return True
    except:
        return False

if is_colab():
    class Color:
        G = ""
        DG = ""
        GR = ""
        RESET = ""
else:
    class Color:
        G = "\033[92m"
        DG = "\033[32m"
        GR = "\033[90m"
        RESET = "\033[0m"

def clear():
    os.system("cls" if os.name == "nt" else "clear")

def type_effect(text, delay=0.014):
    for c in text:
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(delay)
    print()

def wait_enter():
    input(Color.DG + "\nTekan ENTER untuk melanjutkan..." + Color.RESET)

def skull_loading():
    tengkorak = Color.G + r"""
____________________
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║╔═══════╗
╚════════════╝
  ║██████████╚╗
  ║██╔══╗█╔═╗█║
  ║██║╬╔╝█╚╗║█║
  ║██╚═╝█║█╚╝█║
  ╚╗█████████═╝
     ╚╗║╠╩╩╩╩╩╝
        ║║┈┈┈█▐█████▒.｡oO
        ║██╠╦╦╦╗
        ╚╗██████
           ╚════╝

          AMBATUCER AI
    """ + Color.RESET

    total = 2.2
    length = 40

    if is_colab():
        print(tengkorak)
        for i in range(101):
            progress = "#" * (i * length // 100)
            space = " " * (length - len(progress))
            sys.stdout.write(Color.G + f"\r[{progress}{space}] {i}% " + Color.RESET)
            sys.stdout.flush()
            time.sleep(total / 100)
        print()
        return

    for i in range(101):
        clear()
        print(tengkorak)
        progress = "#" * (i * length // 100)
        space = " " * (length - len(progress))
        print(Color.G + f"[{progress}{space}] {i}%" + Color.RESET)
        time.sleep(total / 100)

def panel(text):
    print(Color.GR + "─" * 70 + Color.RESET)
    print(Color.G + text + Color.RESET)
    print(Color.GR + "─" * 70 + Color.RESET)

def header(title):
    clear()
    gar = "═" * 70
    print(Color.G + "╔" + gar + "╗" + Color.RESET)
    print(Color.G + "║" + Color.RESET + f"{title:^70}" + Color.G + "║" + Color.RESET)
    print(Color.G + "╚" + gar + "╝" + Color.RESET)
    print()

def loading(text):
    for i in range(3):
        sys.stdout.write(Color.G + f"\r{text}{'.' * (i+1)}   " + Color.RESET)
        sys.stdout.flush()
        time.sleep(0.35)
    print()

def cek_kesehatan_mental():
    header("CEK KESEHATAN MENTAL")

    pertanyaan = [
        "Seberapa sering kamu merasa cemas?",
        "Seberapa sering kamu sulit tidur?",
        "Seberapa sering kamu merasa sedih?",
        "Seberapa sering kamu kehilangan minat?",
        "Seberapa sering kamu merasa lelah?",
        "Seberapa sering kamu sulit konsentrasi?",
        "Seberapa sering kamu merasa tidak berharga?",
        "Seberapa sering kamu mudah marah?",
        "Seberapa sering kamu merasa terbebani?",
        "Seberapa sering kamu menghindari aktivitas?"
    ]

    panel("Skala: 1-Tidak Pernah | 2-Jarang | 3-Kadang | 4-Sering | 5-Selalu")

    skor = 0
    for p in pertanyaan:
        type_effect(Color.G + p + Color.RESET)
        while True:
            j = input(Color.G + "Jawab (1-5): " + Color.RESET).strip()
            if j.isdigit() and 1 <= int(j) <= 5:
                skor += int(j)
                print()
                break
            type_effect(Color.G + "Input harus angka 1-5." + Color.RESET)

    loading("Menganalisis")
    header("HASIL")

    print(Color.G + f"Total Skor: {skor}/50\n" + Color.RESET)

    if skor <= 15:
        type_effect("Kondisimu stabil dan cukup baik 🙂")
    elif skor <= 30:
        type_effect("Ada tanda stres ringan. Kamu perlu lebih istirahat.")
    elif skor <= 40:
        type_effect("Tekanan emosional sedang. Perlu perhatian lebih.")
    else:
        type_effect("Stres tinggi terdeteksi. Kamu butuh dukungan segera.")

    print()
    panel("Feedback Tambahan")

    if skor <= 15:
        type_effect("• Pertahankan kebiasaan baik seperti tidur teratur.")
        type_effect("• Jaga hubungan sosial agar tetap stabil.")
        type_effect("• Luangkan waktu untuk kegiatan positif.")
    elif skor <= 30:
        type_effect("• Coba latihan pernapasan atau meditasi ringan.")
        type_effect("• Kurangi penggunaan HP sebelum tidur.")
        type_effect("• Sempatkan olahraga ringan 10–20 menit.")
    elif skor <= 40:
        type_effect("• Tanda kelelahan mental mulai muncul.")
        type_effect("• Ceritakan masalahmu ke orang yang kamu percaya.")
        type_effect("• Kurangi beban tugas jika memungkinkan.")
        type_effect("• Jika berlanjut, pertimbangkan konsultasi profesional.")
    else:
        type_effect("• Tingkat stresmu tinggi, kamu tidak sendiri.")
        type_effect("• Sangat disarankan berbicara ke guru BK/psikolog.")
        type_effect("• Istirahat cukup dan jauhi tekanan sementara.")
        type_effect("• Prioritaskan kesehatan mental.")

    print()
    panel("Rekomendasi Harian")
    type_effect("• Tidur cukup 7–9 jam.")
    type_effect("• Minum air, makan teratur.")
    type_effect("• Jauhi drama/konflik.")
    type_effect("• Kurangi overthinking sebelum tidur.")

    wait_enter()

def anti_bullying():
    header("ANTI BULLYING CHECK")

    type_effect("Jawab pertanyaan berikut...")

    q1 = input("Pernah melihat bullying? (ya/tidak): ").strip().lower()
    q2 = input("Apa yang kamu lakukan? (diam/melapor/menolong/membully): ").strip().lower()
    q3 = input("Menurutmu penyebab bullying?: ").strip()
    q4 = input("Apa tindakan terbaik jika temanmu dibully?: ").strip()

    loading("Memproses")
    header("HASIL")

    type_effect(f"✔ Pengalaman: {q1}")
    type_effect(f"✔ Tindakan: {q2}")
    type_effect(f"✔ Penyebab: {q3}")
    type_effect(f"✔ Saran terbaik: {q4}")

    print()
    panel("Analisa & Saran Utama")

    if q2 == "diam":
        type_effect("• Diam bukan pilihan terbaik. Korban bisa merasa sendirian.")
    elif q2 == "melapor":
        type_effect("• Keputusan tepat! Melapor dapat menyelamatkan korban.")
    elif q2 == "menolong":
        type_effect("• Sangat baik! Menolong membuat korban merasa tidak sendirian.")
    elif q2 == "membully":
        type_effect("• Bullying berdampak berat bagi korban dan pelaku.")
    else:
        type_effect("• Jawaban diterima. Pastikan tindakanmu aman dan benar.")

    print()
    panel("Feedback Tambahan")

    type_effect("• Bullying dapat merusak mental korban hingga jangka panjang.")
    type_effect("• Banyak pelaku bully berasal dari masalah pribadi.")
    type_effect("• Mengabaikan bullying membuat pelaku makin berani.")
    type_effect("• Dukungan kecil dari teman bisa menyelamatkan seseorang.")

    print()
    panel("Cara Efektif Menghadapi Bullying")

    type_effect("1. Jangan melawan sendirian, cari bantuan guru/teman.")
    type_effect("2. Catat detail kejadian jika ingin melapor.")
    type_effect("3. Tenangkan korban dan beri rasa aman.")
    type_effect("4. Jangan membalas dengan kekerasan.")
    type_effect("5. Edukasi teman lain tentang bahaya bullying.")

    wait_enter()

def main():
    skull_loading()
    time.sleep(0.5)

    cek_kesehatan_mental()
    anti_bullying()

    header("SELESAI")
    type_effect("Terima kasih telah menggunakan program ini.")
    wait_enter()

if __name__ == "__main__":
    main()